# Generated by Django 4.2.1 on 2023-06-02 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('question', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('answer', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('users_completed', models.ManyToManyField(related_name='quiz_users_completed', to=settings.AUTH_USER_MODEL)),
                ('users_perform', models.ManyToManyField(related_name='quiz_users_perform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('quiz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quiz.quiz')),
            ],
        ),
    ]
