# Generated by Django 4.2.1 on 2023-06-04 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_alter_quiz_answer_alter_quiz_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users_completed',
            field=models.ManyToManyField(blank=True, related_name='quiz_users_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
